name: test
on: pull_request
jobs:
  run-test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
        env:
          BEXXTEBOT_TOKEN: ${{ secrets.BEXXTEBOT_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
      - run: npm install
      - run: npm test